services:
  - type: web
    name: nextfinanceapp
    env: node
    plan: free

    repo: https://github.com/LevdanskyVitaliy/NextFinanceApp
    branch: main
    rootDir: src

    buildCommand: npm install && npm run build
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
