services:
  - type: web
    name: nextfinanceapp
    runtime: javascript
    repo: https://github.com/LevdanskyVitaliy/NextFinanceApp
    branch: main
    rootDir: src
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 3000
